language: c
sudo: false
addons:
  apt:
    packages:
      - texinfo

os:
  - osx
  - linux

osx_image: xcode7

compiler:
  - gcc
  - clang

script:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]] && [[ "${CC}" == "gcc" ]]; then
        brew install gcc48;
        export CC=gcc-4.8;
        export CXX=g++-4.8;
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        export ARB_TEST_MULTIPLIER=0.1;
    fi
  - ./.build_dependencies
  - ./configure --with-mpir=$HOME/deps --with-mpfr=$HOME/deps --with-flint=$HOME/deps --prefix=$HOME/deps
  - make -j4
  - make install
  - make check

